print True == 1
print True != 1
print True == 0
print True != 0
print True == 2
print True != 2
print False == 0
print False != 0
print False == 1
print False != 1
print [] == True
print [] != True
print [] == False
print [] != False
print [1] == True
print [1] != True
print [1] == False
print [1] != False
